# -*- coding: utf-8 -*-
"""168 Managers with at Least 5 Direct Reports.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WygP89VfgvMWrGX7eVIF4n9-ERMtEkqr
"""

import pandas as pd

def find_managers(employee: pd.DataFrame) -> pd.DataFrame:
    managers = employee.groupby('managerId').size().reset_index(name='count')
    managers = managers[managers['count'] >= 5]
    result = managers.merge(
        employee,
        left_on = 'managerId',
        right_on = 'id',
        how = 'inner'
    )[['name']]

    return result